-- MySQL Script generated by MySQL Workbench
-- Mon Dec 15 12:06:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bluewave_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bluewave_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bluewave_db` DEFAULT CHARACTER SET utf8 ;
USE `Bluewave_db` ;

-- -----------------------------------------------------
-- Table `Bluewave_db`.`Guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`Guest` (
  `Guest_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Phone` CHAR(10) NOT NULL,
  `Email` VARCHAR(100) NULL,
  `City` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Guest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bluewave_db`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`room_type` (
  `room_type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(50) NOT NULL,
  `base_price` DECIMAL(10,2) NOT NULL,
  `max_occupancy` SMALLINT NOT NULL,
  PRIMARY KEY (`room_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bluewave_db`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`room` (
  `room_id` INT NOT NULL,
  `room_number` VARCHAR(10) NOT NULL,
  `room_type_id` INT NOT NULL,
  `floor` SMALLINT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_room_roomtype_idx` (`room_type_id` ASC),
  CONSTRAINT `fk_room_roomtype`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `Bluewave_db`.`room_type` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bluewave_db`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`Booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `guest_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `check_in` DATE NOT NULL,
  `check_out` DATE NOT NULL,
  `num_guests` SMALLINT NOT NULL,
  `booking_status` VARCHAR(20) NOT NULL,
  `booked_on` DATE NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `fk_booking_guest_idx` (`guest_id` ASC),
  INDEX `fk_booking_room_idx` (`room_id` ASC),
  CONSTRAINT `fk_booking_guest`
    FOREIGN KEY (`guest_id`)
    REFERENCES `Bluewave_db`.`Guest` (`Guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `Bluewave_db`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bluewave_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `payment_date` DATETIME NULL,
  `method` VARCHAR(20) NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payment_booking_idx` (`booking_id` ASC),
  CONSTRAINT `fk_payment_booking`
    FOREIGN KEY (`booking_id`)
    REFERENCES `Bluewave_db`.`Booking` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bluewave_db`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`department` (
  `Dept_id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bluewave_db`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`staff` (
  `staff_id` INT NOT NULL AUTO_INCREMENT,
  `staff_name` VARCHAR(50) NOT NULL,
  `phone` CHAR(10) NULL,
  `email` VARCHAR(100) NULL,
  `role` VARCHAR(40) NOT NULL,
  `dept_id` INT NOT NULL,
  `hire_date` DATE NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`staff_id`),
  INDEX `fk_staff_department_idx` (`dept_id` ASC),
  CONSTRAINT `fk_staff_department`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Bluewave_db`.`department` (`Dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bluewave_db`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`service` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(60) NOT NULL,
  `base_price` DECIMAL(10,2) NOT NULL,
  `dept_id` INT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `fk_service_department_idx` (`dept_id` ASC),
  CONSTRAINT `fk_service_department`
    FOREIGN KEY (`dept_id`)
    REFERENCES `Bluewave_db`.`department` (`Dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bluewave_db`.`service_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bluewave_db`.`service_booking` (
  `sb_id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `service_date` DATETIME NULL,
  `qty` SMALLINT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`sb_id`),
  INDEX `fk_sb_booking_idx` (`booking_id` ASC),
  INDEX `fk_sb_service_idx` (`service_id` ASC),
  CONSTRAINT `fk_sb_booking`
    FOREIGN KEY (`booking_id`)
    REFERENCES `Bluewave_db`.`Booking` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sb_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `Bluewave_db`.`service` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
